export { StudentRepository } from './studentRepository.js'
export { ClassesRepository } from './classesRepository.js'
export { EnrollmentsRepository } from './enrollmentsRepository.js'
export { ClasstypesRepository } from './classtypesRepository.js'
export { UsersRepository } from './usersRepository.js'
export { RolesRepository } from './rolesRepository.js'
export { RolepermissionsRepository } from './rolepermissionsRepository.js'
export { PermissionsRepository } from './permissionsRepository.js'
