export { PeopleRepository } from './peopleRepository.js'
export { ClassesRepository } from './classesRepository.js'
export { EnrollmentsRepository } from './enrollmentsRepository.js'
export { ClasstypesRepository } from './classtypesRepository.js'
export { UsersRepository } from './usersRepository.js'
